# MetalLB
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metal-lb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oithxs/hira-chan.git
    targetRevision: main
    path: production/manifests/apps/cluster-wide-apps/metallb/
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# Ingress-Nginx
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oithxs/hira-chan.git
    targetRevision: main
    path: production/manifests/apps/cluster-wide-apps/ingress-nginx/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# cert-manager
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://charts.jetstack.io"
    targetRevision: v1.10.1
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---

