version: '3'
services:
  app:
    container_name: laravel-app
    build: ./docker/php
    volumes:
      - .:/var/www
      - ./docker/php/postfix:/etc/postfix/sasl
    depends_on:
      - db
    tty: true

  nginx:
    image: nginx
    container_name: laravel-nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
    tty: true

  db:
    image: mysql:5.7
    container_name: laravel-db
    environment:
      MYSQL_DATABASE: forum
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=rootpass
    ports:
      - 4040:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
    tty: true
